### ISSUE TITLE
Repository is empty for paper: The Pragmatics behind Politics: Modelling Metaphor, Framing and Emotion in Political Discourse

### ISSUE THREAD

**Issue by ChristianStoll** [LittlePea13/mtl_political_discourse#1]
Hi,

I was reading your paper for a seminar at my university: _The Pragmatics behind Politics: Modelling Metaphor, Framing and
Emotion in Political Discourse_ and wanted to take a look at the code you wanted to publish here. Unfortunately this repository is empty. 
Could you please upload your code or tell me if and where I can find it?

Best Regards

**Comment by LittlePea13** [comment]
Hi  @ChristianStoll.
I have been meaning to update the repo but haven't found the time as I wanted to clean the training code. 

I have added the file with the pytorch code for the models used in the paper for the time being. Let me know if you need any help.

Feel free to contact me at perelluis1993@gmail.com if you need any further help with the code.

Also out of curiosity, in which university/seminar did you look at the paper?

**Comment by ChristianStoll** [comment]
Hi @LittlePea13,

Thank you very much for your fast reaction and the pytorch code!

I am currently studying in my master degree at Technical University Darmstadt. The seminar is called Deep Learning for Digital Humanities by Dr. rer. pol. Steffen Eger.

Best Regards
